### ISSUE TITLE
Error adding item 1 to DynamoDB - Auth or endpoint url problem?

### ISSUE THREAD

**Issue by camstuart** [camstuart/tech-spike-serverless#1]
The dynamodb has not had it's collection/table set up yet, but when running the code the following error presents:

```
=============
myFunction invoked with event body:  { id: '1', message: 'Out here on the perimeter, we are...' }
Error adding item 1 to DynamoDB: UnrecognizedClientException: The security token included in the request is invalid.
```

The aws cli supports the `--endpoint-url` like so:

```bash
aws dynamodb list-tables --endpoint-url http://localhost:8000/
```

Which confirms dynamo is operational and can be connected to from the host. AFAIK local dynamo does not need credentials, only that the values are present.

The existing environment variables are set from `.env`:

```bash
env | grep AWS
AWS_ACCESS_KEY_ID=local
AWS_DYNAMODB_ENDPOINT=http://localhost:8000 # <---- may not be working as expected?
AWS_REGION=ap-southeast-2
AWS_SECRET_ACCESS_KEY=local
```

These match the configuration in `docker-compose.local.yml` and thus _should_ work

```yaml
environment:
        DYNAMO_ENDPOINT: "http://dynamodb:8000"
        AWS_REGION: "ap-southest-2"
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
```
